const btn = document.getElementById('btn');
const container = document.getElementById('container');

btn.addEventListener('click', () => {
    createNotification();
});

function createNotification() {
    const note = document.createElement('div');
    note.classList.add('message');

    note.innerText = "Hello, this notification is generated by JavaScript.";
    container.appendChild(note);
    setTimeout(() => {
        note.remove();
    },
        3000);

}